INSERT INTO users(first,last,email,password,role) VALUES('James','Rick','jr@email.com','123456','jobseeker');
INSERT INTO users(first,last,email,password,role) VALUES('John','Richards','jr2@email.com','123456','jobseeker');
INSERT INTO users(first,last,email,password,role) VALUES('Ricardo','Spencer','rs@email.com','123456','jobseeker');
INSERT INTO users(first,last,email,password,role) VALUES('Isaias','Nuno','in@email.com','123456','admin');
INSERT INTO users(first,last,email,password,role) VALUES('Bobert','Guster','bg@email.com','123456','jobseeker');
INSERT INTO users(first,last,email,password,role) VALUES('Samantha','Bobby','sb@email.com','123456','jobseeker');
INSERT INTO users(first,last,email,password,role) VALUES('John','Moore','jm@email.com','123456','jobseeker');

INSERT INTO applications(user_id,company,job_title,deadline,post_url,description,note,status,salary,location) VALUES (1, 'Google', 'Software Developer', current_date + interval '7 day', 'https://www.linkedin.com/jobs/', 'A job at a place', 'apply soon', 'Interviewing', 125000, 'colorado springs');
INSERT INTO applications(user_id,company,job_title,deadline,post_url,description,note,status,salary,location) VALUES (2, 'Google', 'Software Developer', current_date + interval '7 day', 'https://www.linkedin.com/jobs/', 'A job at a place', 'apply soon', 'Interviewing', 125000, 'colorado springs');
INSERT INTO applications(user_id,company,job_title,deadline,post_url,description,note,status,salary,location) VALUES (3, 'Google', 'Software Developer', current_date + interval '7 day', 'https://www.linkedin.com/jobs/', 'A job at a place', 'apply soon', 'Interviewing', 125000, 'colorado springs');
INSERT INTO applications(user_id,company,job_title,deadline,post_url,description,note,status,salary,location) VALUES (4, 'Google', 'Software Developer', current_date + interval '7 day', 'https://www.linkedin.com/jobs/', 'A job at a place', 'apply soon', 'Interviewing', 125000, 'colorado springs');
INSERT INTO applications(user_id,company,job_title,deadline,post_url,description,note,status,salary,location) VALUES (5, 'Google', 'Software Developer', current_date + interval '7 day', 'https://www.linkedin.com/jobs/', 'A job at a place', 'apply soon', 'Interviewing', 125000, 'colorado springs');
INSERT INTO applications(user_id,company,job_title,deadline,post_url,description,note,status,salary,location) VALUES (6, 'Google', 'Software Developer', current_date + interval '7 day', 'https://www.linkedin.com/jobs/', 'A job at a place', 'apply soon', 'Interviewing', 125000, 'colorado springs');
INSERT INTO applications(user_id,company,job_title,deadline,post_url,description,note,status,salary,location) VALUES (7, 'Google', 'Software Developer', current_date + interval '7 day', 'https://www.linkedin.com/jobs/', 'A job at a place', 'apply soon', 'Interviewing', 125000, 'colorado springs');
INSERT INTO applications(user_id,company,job_title,deadline,post_url,description,note,status,salary,location) VALUES (1, 'Facebook', 'Software Engineer', current_date + interval '7 day', 'https://www.linkedin.com/jobs/', 'A important job at a nonimportant place', 'apply whenever', 'Interviewing', 100000, 'denver');
INSERT INTO applications(user_id,company,job_title,deadline,post_url,description,note,status,salary,location) VALUES (2, 'Facebook', 'Software Engineer', current_date + interval '7 day', 'https://www.linkedin.com/jobs/', 'A important job at a nonimportant place', 'apply whenever', 'Interviewing', 100000, 'denver');
INSERT INTO applications(user_id,company,job_title,deadline,post_url,description,note,status,salary,location) VALUES (3, 'Facebook', 'Software Engineer', current_date + interval '7 day', 'https://www.linkedin.com/jobs/', 'A important job at a nonimportant place', 'apply whenever', 'Interviewing', 100000, 'denver');
INSERT INTO applications(user_id,company,job_title,deadline,post_url,description,note,status,salary,location) VALUES (4, 'Facebook', 'Software Engineer', current_date + interval '7 day', 'https://www.linkedin.com/jobs/', 'A important job at a nonimportant place', 'apply whenever', 'Interviewing', 100000, 'denver');
INSERT INTO applications(user_id,company,job_title,deadline,post_url,description,note,status,salary,location) VALUES (5, 'Facebook', 'Software Engineer', current_date + interval '7 day', 'https://www.linkedin.com/jobs/', 'A important job at a nonimportant place', 'apply whenever', 'Interviewing', 100000, 'denver');
INSERT INTO applications(user_id,company,job_title,deadline,post_url,description,note,status,salary,location) VALUES (6, 'Facebook', 'Software Engineer', current_date + interval '7 day', 'https://www.linkedin.com/jobs/', 'A important job at a nonimportant place', 'apply whenever', 'Interviewing', 100000, 'denver');
INSERT INTO applications(user_id,company,job_title,deadline,post_url,description,note,status,salary,location) VALUES (7, 'Facebook', 'Software Engineer', current_date + interval '7 day', 'https://www.linkedin.com/jobs/', 'A important job at a nonimportant place', 'apply whenever', 'Interviewing', 100000, 'denver');
INSERT INTO applications(user_id,company,job_title,deadline,post_url,description,note,status,salary,location) VALUES (1, 'Mapquest', 'Front End Developer', current_date + interval '7 day', 'https://www.linkedin.com/jobs/', 'Do we really want this job?', 'apply at some point', 'Applying', 60000, 'orlando');
INSERT INTO applications(user_id,company,job_title,deadline,post_url,description,note,status,salary,location) VALUES (2, 'Mapquest', 'Front End Developer', current_date + interval '7 day', 'https://www.linkedin.com/jobs/', 'Do we really want this job?', 'apply at some point', 'Applying', 60000, 'orlando');
INSERT INTO applications(user_id,company,job_title,deadline,post_url,description,note,status,salary,location) VALUES (3, 'Mapquest', 'Front End Developer', current_date + interval '7 day', 'https://www.linkedin.com/jobs/', 'Do we really want this job?', 'apply at some point', 'Applying', 60000, 'orlando');
INSERT INTO applications(user_id,company,job_title,deadline,post_url,description,note,status,salary,location) VALUES (4, 'Mapquest', 'Front End Developer', current_date + interval '7 day', 'https://www.linkedin.com/jobs/', 'Do we really want this job?', 'apply at some point', 'Applying', 60000, 'orlando');
INSERT INTO applications(user_id,company,job_title,deadline,post_url,description,note,status,salary,location) VALUES (5, 'Mapquest', 'Front End Developer', current_date + interval '7 day', 'https://www.linkedin.com/jobs/', 'Do we really want this job?', 'apply at some point', 'Applying', 60000, 'orlando');
INSERT INTO applications(user_id,company,job_title,deadline,post_url,description,note,status,salary,location) VALUES (6, 'Mapquest', 'Front End Developer', current_date + interval '7 day', 'https://www.linkedin.com/jobs/', 'Do we really want this job?', 'apply at some point', 'Applying', 60000, 'orlando');
INSERT INTO applications(user_id,company,job_title,deadline,post_url,description,note,status,salary,location) VALUES (7, 'Mapquest', 'Front End Developer', current_date + interval '7 day', 'https://www.linkedin.com/jobs/', 'Do we really want this job?', 'apply at some point', 'Applying', 60000, 'orlando');

INSERT INTO comments(user_id,application_id,body) VALUES (1,1,'Some sort of text about the application');
INSERT INTO comments(user_id,application_id,body) VALUES (2,3,'Some sort of text about the application');
INSERT INTO comments(user_id,application_id,body) VALUES (3,4,'Some sort of text about the application');
INSERT INTO comments(user_id,application_id,body) VALUES (4,4,'Some sort of text about the application');
INSERT INTO comments(user_id,application_id,body) VALUES (5,4,'Some sort of text about the application');
INSERT INTO comments(user_id,application_id,body) VALUES (6,5,'Some sort of text about the application');
INSERT INTO comments(user_id,application_id,body) VALUES (7,5,'Some sort of text about the application');
INSERT INTO comments(user_id,application_id,body) VALUES (1,6,'Some sort of text about the application');
INSERT INTO comments(user_id,application_id,body) VALUES (2,7,'Some sort of text about the application');
INSERT INTO comments(user_id,application_id,body) VALUES (3,4, 'Some sort of text about the application');
INSERT INTO comments(user_id,application_id,body) VALUES (4,3, 'Some sort of text about the application');
INSERT INTO comments(user_id,application_id,body) VALUES (5,4, 'Some sort of text about the application');
INSERT INTO comments(user_id,application_id,body) VALUES (6,5, 'Some sort of text about the application');
INSERT INTO comments(user_id,application_id,body) VALUES (7,5, 'Some sort of text about the application');
INSERT INTO comments(user_id,application_id,body) VALUES (1,2, 'Some sort of text about the application');
INSERT INTO comments(user_id,application_id,body) VALUES (2,2, 'Some sort of text about the application');
INSERT INTO comments(user_id,application_id,body) VALUES (3,8, 'Do we really want this job?');
INSERT INTO comments(user_id,application_id,body) VALUES (4,9, 'Do we really want this job?');
INSERT INTO comments(user_id,application_id,body) VALUES (5,10, 'Do we really want this job?');
INSERT INTO comments(user_id,application_id,body) VALUES (6,12, 'Do we really want this job?');
INSERT INTO comments(user_id,application_id,body) VALUES (7,12, 'Do we really want this job?');
INSERT INTO comments(user_id,application_id,body) VALUES (1,14, 'Do we really want this job?');
INSERT INTO comments(user_id,application_id,body) VALUES (2,15, 'Do we really want this job?');

INSERT INTO updates(application_id,body) VALUES (1,'S these are updates about stuff');
INSERT INTO updates(application_id,body) VALUES (3,'S these are updates about stuff');
INSERT INTO updates(application_id,body) VALUES (4,'S these are updates about stuff');
INSERT INTO updates(application_id,body) VALUES (4,'S these are updates about stuff');
INSERT INTO updates(application_id,body) VALUES (4,'S these are updates about stuff');
INSERT INTO updates(application_id,body) VALUES (5,'S these are updates about stuff');
INSERT INTO updates(application_id,body) VALUES (5,'S these are updates about stuff');
INSERT INTO updates(application_id,body) VALUES (6,'S these are updates about stuff');
INSERT INTO updates(application_id,body) VALUES (7,'S these are updates about stuff');
INSERT INTO updates(application_id,body) VALUES (4, ' these are updates about stuffn');
INSERT INTO updates(application_id,body) VALUES (3, ' these are updates about stuffn');
INSERT INTO updates(application_id,body) VALUES (4, ' these are updates about stuffn');
INSERT INTO updates(application_id,body) VALUES (5, ' these are updates about stuffn');
INSERT INTO updates(application_id,body) VALUES (5, ' these are updates about stuffn');
INSERT INTO updates(application_id,body) VALUES (2, ' these are updates about stuffn');
INSERT INTO updates(application_id,body) VALUES (2, ' these are updates about stuffn');
INSERT INTO updates(application_id,body) VALUES (8, 'Update update update update');
INSERT INTO updates(application_id,body) VALUES (9, 'Update update update update');
INSERT INTO updates(application_id,body) VALUES (10, 'More updates or something');
INSERT INTO updates(application_id,body) VALUES (12, 'More updates or something');
INSERT INTO updates(application_id,body) VALUES (12, 'More updates or something');
INSERT INTO updates(application_id,body) VALUES (14, 'More updates or something');
INSERT INTO updates(application_id,body) VALUES (15, 'More updates or something');

INSERT INTO groups(user_id, group_name) VALUES (1, 'MCSP-10');
INSERT INTO groups(user_id, group_name) VALUES (2, 'MCSP-10');
INSERT INTO groups(user_id, group_name) VALUES (3, 'MCSP-10');
INSERT INTO groups(user_id, group_name) VALUES (4, 'MCSP-10');
INSERT INTO groups(user_id, group_name) VALUES (4, 'MCSP-11');
INSERT INTO groups(user_id, group_name) VALUES (5, 'MCSP-10');
INSERT INTO groups(user_id, group_name) VALUES (6, 'MCSP-11');
INSERT INTO groups(user_id, group_name) VALUES (7, 'MCSP-11');